//
//  TextExportService.swift
//  Latynize
//
//  Created by Izbassar Orynbassar on 22.04.2026.
//

import Foundation

/// Generates plain text files from ConversionRecord instances.
final class TextExportService {
    
    static let shared = TextExportService()
    private init() {}
    
    func exportSingle(_ record: ConversionRecord) -> URL? {
        let content = buildSingleText(record)
        return writeFile(content: content, name: "Latynize-Export")
    }
    
    func exportBulk(_ records: [ConversionRecord], title: String) -> URL? {
        guard !records.isEmpty else { return nil }
        let content = buildBulkText(records, title: title)
        return writeFile(content: content, name: "Latynize-Export")
    }
    
    // MARK: - Builders
    
    private func buildSingleText(_ record: ConversionRecord) -> String {
        var output = ""
        output += "LATYNIZE — Kazakh Script Converter\n"
        output += String(repeating: "=", count: 50) + "\n\n"
        
        output += "ORIGINAL:\n"
        output += record.inputText + "\n\n"
        
        output += "CONVERTED:\n"
        output += record.outputText + "\n\n"
        
        output += String(repeating: "-", count: 50) + "\n"
        output += "Standard: \(record.alphabetVersion == "2021" ? "Standard 2021" : "Legacy 2018")\n"
        output += "Direction: \(record.direction.label)\n"
        output += "Created: \(record.createdAt.formatted(date: .long, time: .shortened))\n\n"
        
        output += "Generated by Latynize\n"
        return output
    }
    
    private func buildBulkText(_ records: [ConversionRecord], title: String) -> String {
        var output = ""
        output += "LATYNIZE — \(title)\n"
        output += String(repeating: "=", count: 50) + "\n"
        output += "\(records.count) conversions\n\n"
        
        for (index, record) in records.enumerated() {
            output += "#\(index + 1) · \(record.createdAt.formatted(date: .abbreviated, time: .shortened))\n"
            output += record.inputText + "\n"
            output += "→ " + record.outputText + "\n\n"
        }
        
        output += String(repeating: "-", count: 50) + "\n"
        output += "Generated by Latynize\n"
        return output
    }
    
    // MARK: - File Writer
    
    private func writeFile(content: String, name: String) -> URL? {
        let tempDir = FileManager.default.temporaryDirectory
        let url = tempDir.appendingPathComponent("\(name).txt")
        
        do {
            try content.write(to: url, atomically: true, encoding: .utf8)
            return url
        } catch {
            print("Text export failed: \(error)")
            return nil
        }
    }
}
